FROM {{ nginx.img }}:{{ nginx.img_tag }}
WORKDIR /opt
RUN mkdir ./{{ nginx.cert_folder }}
RUN mkdir ./{{ nginx.logs_folder }}
# WORKDIR /opt/{{ nginx.cert_folder }}
# COPY ./private_key.pem ./
# COPY ./public_key.crt ./
# COPY ./rootCA.crt ./
WORKDIR /etc/nginx/conf.d
RUN rm -f ./default.conf
COPY ./default.conf ./
RUN chmod 766 /etc/nginx/conf.d

EXPOSE {{ nginx.out_port }}
